// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYfCWnb8kCLtgqEIt71ZYxNZ5cvtDfH_w',
    appId: '1:804384212331:web:98085ea97fe84e6893b82e',
    messagingSenderId: '804384212331',
    projectId: 'my-todo-flutter',
    authDomain: 'my-todo-flutter.firebaseapp.com',
    storageBucket: 'my-todo-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGB1FyVWOGIQNtysg8WjxgZ2vPGG-zml0',
    appId: '1:804384212331:android:660b173719b78b4d93b82e',
    messagingSenderId: '804384212331',
    projectId: 'my-todo-flutter',
    storageBucket: 'my-todo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD82Gf0lJxGpGUKh-XXZPWYrl9uSy_XPmY',
    appId: '1:804384212331:ios:446013e8f1f7226093b82e',
    messagingSenderId: '804384212331',
    projectId: 'my-todo-flutter',
    storageBucket: 'my-todo-flutter.appspot.com',
    iosClientId: '804384212331-2v6q4674baslvcopo4m36d399qh12r6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.flutterTodo',
  );
}
