/// Generated by Flutter GetX Starter on 2022-10-21 09:47

import 'package:flutter/material.dart';
import 'package:flutter_todo_mine/screens/screen_login.dart';
import 'package:flutter_todo_mine/screens/screen_splash.dart';
import 'package:get/get_navigation/get_navigation.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      home: ScreenSplash(),
    );
  }
}